using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TestAmbra.AmbraModels
{
    public class Permissions
    {
        public int study_audio_play { get; set; }
        public int node_view { get; set; }
        public int study_share_user { get; set; }
        public int user_modify_sharecode { get; set; }
        public int radreport_edit { get; set; }
        public int message_view { get; set; }
        public int study_download_viewer { get; set; }
        public int study_search_require_patient_name { get; set; }
        public int study_share_location { get; set; }
        public int link_edit_upload { get; set; }
        public int study_report_detail { get; set; }
        public int study_duplicate { get; set; }
        public int analytics_view { get; set; }
        public int study_report_hl7_view_unapproved { get; set; }
        public int customfield_view { get; set; }
        public int radreport_view { get; set; }
        public int user_request_access { get; set; }
        public string study_field_modality { get; set; }
        public int link_view { get; set; }
        public int user_modify_defaults { get; set; }
        public int hl7_template_view { get; set; }
        public string study_field_patientid { get; set; }
        public int dictionary_view { get; set; }
        public int annotation_view_only_own { get; set; }
        public int purge_edit { get; set; }
        public int study_download { get; set; }
        public int order_view { get; set; }
        public int study_status_edit { get; set; }
        public int purge_view { get; set; }
        public string study_field_study_date { get; set; }
        public int study_star { get; set; }
        public int study_delete { get; set; }
        public int study_comment_view { get; set; }
        public int location_edit { get; set; }
        public string webhook_view { get; set; }
        public int study_report_delete_unapproved { get; set; }
        public int study_thin { get; set; }
        public int role_view { get; set; }
        public int study_report_view_approved { get; set; }
        public int study_edit { get; set; }
        public int study_search_require_patientid { get; set; }
        public int destination_view { get; set; }
        public int account_user_edit { get; set; }
        public int channel_activity { get; set; }
        public int meeting_view { get; set; }
        public int account_edit { get; set; }
        public int study_share_email { get; set; }
        public int route_view { get; set; }
        public int validate_edit { get; set; }
        public string study_field_patient_birth_date { get; set; }
        public int study_report_delete_approved { get; set; }
        public int study_move { get; set; }
        public int hl7_transform_edit { get; set; }
        public int keyimage_edit { get; set; }
        public int meeting_edit { get; set; }
        public int study_share_rsna { get; set; }
        public int case_edit { get; set; }
        public int location_view { get; set; }
        public int radreport_html_format { get; set; }
        public int destination_search { get; set; }
        public int channel_study { get; set; }
        public int user_modify_notifications { get; set; }
        public int message_edit { get; set; }
        public int study_push { get; set; }
        public int study_share_group { get; set; }
        public int study_edit_approved { get; set; }
        public int hl7_template_edit { get; set; }
        public int study_search_require_patient_birth_date { get; set; }
        public string viewer_config { get; set; }
        public int link_edit { get; set; }
        public int study_upload_validate { get; set; }
        public int study_view { get; set; }
        public int study_browse { get; set; }
        public int patient_edit { get; set; }
        public int study_status_view { get; set; }
        public int patient_view { get; set; }
        public int node_edit { get; set; }
        public int group_view { get; set; }
        public int study_download_iso { get; set; }
        public int group_edit { get; set; }
        public int account_view { get; set; }
        public int study_share_account { get; set; }
        public int study_audio_record { get; set; }
        public int can_proxy_login { get; set; }
        public int study_search_require_accession_number { get; set; }
        public int destination_search_mwl { get; set; }
        public int role_edit { get; set; }
        public int route_edit { get; set; }
        public int case_view { get; set; }
        public int study_report_upload { get; set; }
        public int study_report_delete { get; set; }
        public int hl7_transform_view { get; set; }
        public int user_edit { get; set; }
        public int study_manual_route { get; set; }
        public int annotation_view { get; set; }
        public int study_sync { get; set; }
        public int destination_edit { get; set; }
        public int audit_view { get; set; }
        public int study_share_share_code { get; set; }
        public int study_search_require_patient_sex { get; set; }
        public int study_delete_image { get; set; }
        public string study_field_patient_sex { get; set; }
        public int validate_view { get; set; }
        public int study_upload { get; set; }
        public int keyimage_view { get; set; }
        public int filter_share { get; set; }
        public int study_share { get; set; }
        public int study_report_hl7_view { get; set; }
        public string study_field_study_description { get; set; }
        public int annotation_edit { get; set; }
        public int account_user_view { get; set; }
        public int study_tag { get; set; }
        public string webhook_edit { get; set; }
        public int study_edit_unapproved { get; set; }
        public string study_field_accession_number { get; set; }
        public string study_field_patient_name { get; set; }
        public int study_report_view_unapproved { get; set; }
        public int study_report_view { get; set; }
        public int study_approve { get; set; }
        public int link_direct { get; set; }
        public int order_edit { get; set; }
        public int study_report_upload_unapproved { get; set; }
        public int study_report_hl7_view_approved { get; set; }
        public int study_report_upload_approved { get; set; }
        public string study_field_referring_physician { get; set; }
        public int customfield_edit { get; set; }
        public int dictionary_edit { get; set; }
        public int study_comment_edit { get; set; }
    }
}